/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.campominado;

/**
 *
 * @author erick.ssouza
 */
public class Tabuleiro extends javax.swing.JFrame {

    /**
     * Creates new form Tabuleiro
     */
    public Tabuleiro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        m00 = new javax.swing.JButton();
        m01 = new javax.swing.JButton();
        m08 = new javax.swing.JButton();
        m02 = new javax.swing.JButton();
        m03 = new javax.swing.JButton();
        m04 = new javax.swing.JButton();
        m05 = new javax.swing.JButton();
        m06 = new javax.swing.JButton();
        m07 = new javax.swing.JButton();
        m09 = new javax.swing.JButton();
        m19 = new javax.swing.JButton();
        m16 = new javax.swing.JButton();
        m17 = new javax.swing.JButton();
        m10 = new javax.swing.JButton();
        m11 = new javax.swing.JButton();
        m18 = new javax.swing.JButton();
        m12 = new javax.swing.JButton();
        m13 = new javax.swing.JButton();
        m14 = new javax.swing.JButton();
        m15 = new javax.swing.JButton();
        m29 = new javax.swing.JButton();
        m26 = new javax.swing.JButton();
        m27 = new javax.swing.JButton();
        m20 = new javax.swing.JButton();
        m21 = new javax.swing.JButton();
        m28 = new javax.swing.JButton();
        m22 = new javax.swing.JButton();
        m23 = new javax.swing.JButton();
        m24 = new javax.swing.JButton();
        m25 = new javax.swing.JButton();
        m39 = new javax.swing.JButton();
        m36 = new javax.swing.JButton();
        m37 = new javax.swing.JButton();
        m30 = new javax.swing.JButton();
        m31 = new javax.swing.JButton();
        m38 = new javax.swing.JButton();
        m32 = new javax.swing.JButton();
        m33 = new javax.swing.JButton();
        m34 = new javax.swing.JButton();
        m35 = new javax.swing.JButton();
        m49 = new javax.swing.JButton();
        m46 = new javax.swing.JButton();
        m47 = new javax.swing.JButton();
        m40 = new javax.swing.JButton();
        m41 = new javax.swing.JButton();
        m48 = new javax.swing.JButton();
        m42 = new javax.swing.JButton();
        m43 = new javax.swing.JButton();
        m44 = new javax.swing.JButton();
        m45 = new javax.swing.JButton();
        m59 = new javax.swing.JButton();
        m56 = new javax.swing.JButton();
        m57 = new javax.swing.JButton();
        m50 = new javax.swing.JButton();
        m51 = new javax.swing.JButton();
        m58 = new javax.swing.JButton();
        m52 = new javax.swing.JButton();
        m53 = new javax.swing.JButton();
        m54 = new javax.swing.JButton();
        m55 = new javax.swing.JButton();
        m69 = new javax.swing.JButton();
        m66 = new javax.swing.JButton();
        m67 = new javax.swing.JButton();
        m60 = new javax.swing.JButton();
        m61 = new javax.swing.JButton();
        m68 = new javax.swing.JButton();
        m62 = new javax.swing.JButton();
        m63 = new javax.swing.JButton();
        m64 = new javax.swing.JButton();
        m65 = new javax.swing.JButton();
        m79 = new javax.swing.JButton();
        m76 = new javax.swing.JButton();
        m77 = new javax.swing.JButton();
        m70 = new javax.swing.JButton();
        m71 = new javax.swing.JButton();
        m78 = new javax.swing.JButton();
        m72 = new javax.swing.JButton();
        m73 = new javax.swing.JButton();
        m74 = new javax.swing.JButton();
        m75 = new javax.swing.JButton();
        m89 = new javax.swing.JButton();
        m86 = new javax.swing.JButton();
        m87 = new javax.swing.JButton();
        m80 = new javax.swing.JButton();
        m81 = new javax.swing.JButton();
        m88 = new javax.swing.JButton();
        m82 = new javax.swing.JButton();
        m83 = new javax.swing.JButton();
        m84 = new javax.swing.JButton();
        m85 = new javax.swing.JButton();
        m99 = new javax.swing.JButton();
        m96 = new javax.swing.JButton();
        m97 = new javax.swing.JButton();
        m90 = new javax.swing.JButton();
        m91 = new javax.swing.JButton();
        m98 = new javax.swing.JButton();
        m92 = new javax.swing.JButton();
        m93 = new javax.swing.JButton();
        m94 = new javax.swing.JButton();
        m95 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        m00.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N
        m01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m01ActionPerformed(evt);
            }
        });

        m08.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m09.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N
        m52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m52ActionPerformed(evt);
            }
        });

        m53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m69.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m68.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m79.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m76.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m77.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m71.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m78.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m73.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m74.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m75.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m89.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m86.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m87.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m80.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m81.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m88.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m82.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m83.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m84.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m85.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m99.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m96.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m97.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m90.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m91.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m98.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m92.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N
        m92.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m92ActionPerformed(evt);
            }
        });

        m93.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m94.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        m95.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/campominado/inicio.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(m00, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m01, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m02, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m03, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m04, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m05, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m06, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m07, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m08, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m09, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(m10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(m20, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m23, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m24, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m25, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m26, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m27, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m28, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m29, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(m30, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m31, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m32, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m33, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m34, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m35, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m36, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m37, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m38, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m39, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(m40, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m41, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m42, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m43, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m44, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m45, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m46, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m47, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m48, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m49, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(m50, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m51, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m52, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m53, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m54, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m55, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m56, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m57, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m58, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m59, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(m60, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m61, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m62, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m63, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m64, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m65, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m66, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m67, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m68, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m69, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(m70, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m71, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m72, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m73, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m74, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m75, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m76, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m77, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m78, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m79, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(m80, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m81, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m82, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m83, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m84, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m85, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m86, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m87, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m88, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m89, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(m90, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m91, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m92, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m93, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m94, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m95, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m96, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m97, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m98, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(m99, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(m08, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m07, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m06, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m05, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m04, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m01, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m00, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(m03, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(m02, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(m09, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(m18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(m13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(m12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(m19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(m28, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m27, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m26, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m25, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m24, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m20, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(m23, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(m22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(m29, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(m38, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m37, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m36, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m35, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m34, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m31, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m30, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(m33, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(m32, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(m39, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(m48, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m47, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m46, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m45, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m44, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m41, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m40, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(m43, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(m42, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(m49, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(m58, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m57, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m56, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m55, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m54, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m51, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m50, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m53, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m59, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m52, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(m68, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m67, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m66, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m65, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m64, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m61, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m60, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(m63, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(m62, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(m69, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(m78, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m77, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m76, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m75, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m74, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m71, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m70, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(m73, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(m72, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(m79, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(m88, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m87, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m86, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m85, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m84, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m81, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m80, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(m83, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(m82, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(m89, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(m98, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m97, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m96, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m95, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m94, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m91, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m90, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(m93, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(m92, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(m99, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void m52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m52ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m52ActionPerformed

    private void m92ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m92ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m92ActionPerformed

    private void m01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m01ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tabuleiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tabuleiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tabuleiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tabuleiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tabuleiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton m00;
    private javax.swing.JButton m01;
    private javax.swing.JButton m02;
    private javax.swing.JButton m03;
    private javax.swing.JButton m04;
    private javax.swing.JButton m05;
    private javax.swing.JButton m06;
    private javax.swing.JButton m07;
    private javax.swing.JButton m08;
    private javax.swing.JButton m09;
    private javax.swing.JButton m10;
    private javax.swing.JButton m11;
    private javax.swing.JButton m12;
    private javax.swing.JButton m13;
    private javax.swing.JButton m14;
    private javax.swing.JButton m15;
    private javax.swing.JButton m16;
    private javax.swing.JButton m17;
    private javax.swing.JButton m18;
    private javax.swing.JButton m19;
    private javax.swing.JButton m20;
    private javax.swing.JButton m21;
    private javax.swing.JButton m22;
    private javax.swing.JButton m23;
    private javax.swing.JButton m24;
    private javax.swing.JButton m25;
    private javax.swing.JButton m26;
    private javax.swing.JButton m27;
    private javax.swing.JButton m28;
    private javax.swing.JButton m29;
    private javax.swing.JButton m30;
    private javax.swing.JButton m31;
    private javax.swing.JButton m32;
    private javax.swing.JButton m33;
    private javax.swing.JButton m34;
    private javax.swing.JButton m35;
    private javax.swing.JButton m36;
    private javax.swing.JButton m37;
    private javax.swing.JButton m38;
    private javax.swing.JButton m39;
    private javax.swing.JButton m40;
    private javax.swing.JButton m41;
    private javax.swing.JButton m42;
    private javax.swing.JButton m43;
    private javax.swing.JButton m44;
    private javax.swing.JButton m45;
    private javax.swing.JButton m46;
    private javax.swing.JButton m47;
    private javax.swing.JButton m48;
    private javax.swing.JButton m49;
    private javax.swing.JButton m50;
    private javax.swing.JButton m51;
    private javax.swing.JButton m52;
    private javax.swing.JButton m53;
    private javax.swing.JButton m54;
    private javax.swing.JButton m55;
    private javax.swing.JButton m56;
    private javax.swing.JButton m57;
    private javax.swing.JButton m58;
    private javax.swing.JButton m59;
    private javax.swing.JButton m60;
    private javax.swing.JButton m61;
    private javax.swing.JButton m62;
    private javax.swing.JButton m63;
    private javax.swing.JButton m64;
    private javax.swing.JButton m65;
    private javax.swing.JButton m66;
    private javax.swing.JButton m67;
    private javax.swing.JButton m68;
    private javax.swing.JButton m69;
    private javax.swing.JButton m70;
    private javax.swing.JButton m71;
    private javax.swing.JButton m72;
    private javax.swing.JButton m73;
    private javax.swing.JButton m74;
    private javax.swing.JButton m75;
    private javax.swing.JButton m76;
    private javax.swing.JButton m77;
    private javax.swing.JButton m78;
    private javax.swing.JButton m79;
    private javax.swing.JButton m80;
    private javax.swing.JButton m81;
    private javax.swing.JButton m82;
    private javax.swing.JButton m83;
    private javax.swing.JButton m84;
    private javax.swing.JButton m85;
    private javax.swing.JButton m86;
    private javax.swing.JButton m87;
    private javax.swing.JButton m88;
    private javax.swing.JButton m89;
    private javax.swing.JButton m90;
    private javax.swing.JButton m91;
    private javax.swing.JButton m92;
    private javax.swing.JButton m93;
    private javax.swing.JButton m94;
    private javax.swing.JButton m95;
    private javax.swing.JButton m96;
    private javax.swing.JButton m97;
    private javax.swing.JButton m98;
    private javax.swing.JButton m99;
    // End of variables declaration//GEN-END:variables
}
